apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hpk4tx1wk-go 
  janus-idp.io/tekton: hpk4tx1wk-go
  backstage.io/kubernetes-id: hpk4tx1wk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hpk4tx1wk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml